# -*- coding: utf-8 -*-
"""FIFA-WORLD-CUP-2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M5uBJQ-Dn_gVrf_fuu5Fum_z1MFqxIrm
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('fifa_world_cup_2026_player_performance.csv')
nRows, nCols = df.shape
df.head()

missing_values = df.isnull().sum()
missing_values = missing_values[missing_values > 0].sort_values(ascending=False)

print("\nMissing Values:")
if missing_values.empty:
    print("No missing values found in the dataset.")
else:
    display(missing_values)

duplicate_rows = df.duplicated().sum()

print(f"\nNumber of Duplicate Rows: {duplicate_rows}")

if duplicate_rows > 0:
    print("Warning: Duplicate rows found. Consider handling them if necessary.")

df.info()

display(df.describe())

fig_age_rating = plt.figure(figsize=(10, 6))
sns.scatterplot(x='age', y='tournament_rating', data=df)
plt.title('Age vs. Tournament Rating')
plt.xlabel('Age')
plt.ylabel('Tournament Rating')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

fig_goals_rating = plt.figure(figsize=(10, 6))
sns.scatterplot(x='total_goals_tournament', y='tournament_rating', data=df)
plt.title('Total Goals in Tournament vs. Tournament Rating')
plt.xlabel('Total Goals in Tournament')
plt.ylabel('Tournament Rating')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

fig_assists_rating = plt.figure(figsize=(10, 6))
sns.scatterplot(x='total_assists_tournament', y='tournament_rating', data=df)
plt.title('Total Assists in Tournament vs. Tournament Rating')
plt.xlabel('Total Assists in Tournament')
plt.ylabel('Tournament Rating')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

fig_minutes_rating = plt.figure(figsize=(10, 6))
sns.scatterplot(x='total_minutes_tournament', y='tournament_rating', data=df)
plt.title('Total Minutes in Tournament vs. Tournament Rating')
plt.xlabel('Total Minutes in Tournament')
plt.ylabel('Tournament Rating')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

fig_pos_rating = plt.figure(figsize=(12, 7))
sns.boxplot(x='position', y='tournament_rating', data=df)
plt.title('Position vs. Tournament Rating')
plt.xlabel('Player Position')
plt.ylabel('Tournament Rating')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

top_teams = df.groupby('team')['tournament_rating'].mean().nlargest(10).index
df_top_teams = df[df['team'].isin(top_teams)]

fig_team_rating = plt.figure(figsize=(12, 7))
sns.boxplot(x='team', y='tournament_rating', data=df_top_teams, order=top_teams)
plt.title('Tournament Rating by Top 10 Teams')
plt.xlabel('Team')
plt.ylabel('Tournament Rating')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

numerical_cols = df.select_dtypes(include=['number']).columns
corr_matrix = df[numerical_cols].corr()

fig_corr = plt.figure(figsize=(20, 18))
sns.heatmap(corr_matrix, annot=False, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix of Numerical Features')
plt.xticks(rotation=90)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

df['match_date'] = pd.to_datetime(df['match_date'])
print("Data types after converting 'match_date':")
df[['match_date']].info()

categorical_cols = df.select_dtypes(include='object').columns

print("Categorical Columns and their unique value counts:")
for col in categorical_cols:
    print(f"{col}: {df[col].nunique()} unique values")

print("\nValue Counts for 'position':")
display(df['position'].value_counts())

print("\nValue Counts for 'preferred_foot':")
display(df['preferred_foot'].value_counts())

corr_threshold = 0.95

high_corr_pairs = []

for i in range(len(corr_matrix.columns)):
    for j in range(i):
        if abs(corr_matrix.iloc[i, j]) > corr_threshold:
            colname1 = corr_matrix.columns[i]
            colname2 = corr_matrix.columns[j]
            high_corr_pairs.append((colname1, colname2, corr_matrix.iloc[i, j]))

if high_corr_pairs:
    print(f"\nHautes corrélations (valeur absolue > {corr_threshold}):")
    for pair in high_corr_pairs:
        print(f"  {pair[0]} et {pair[1]}: {pair[2]:.2f}")
    print("\nConsidérer de supprimer ou de combiner l'une de ces colonnes pour éviter la multicolinéarité si un modèle linéaire est utilisé.")
else:
    print(f"\nPas de paires de colonnes numériques avec une corrélation supérieure à {corr_threshold}.")

df['goals_per_minute'] = df['total_goals_tournament'] / (df['total_minutes_tournament'] + 1e-6)
df['assists_per_minute'] = df['total_assists_tournament'] / (df['total_minutes_tournament'] + 1e-6)

print("\nNouvelles fonctionnalités créées: 'goals_per_minute' et 'assists_per_minute'.")
display(df[['total_goals_tournament', 'total_minutes_tournament', 'goals_per_minute', 'total_assists_tournament', 'assists_per_minute']].head())

"""### Extraction de Fonctionnalités Temporelles à partir de `match_date`

Nous allons extraire l'année, le mois, le jour de la semaine et le jour de l'année de la colonne `match_date` pour capturer d'éventuels motifs saisonniers ou temporels.
"""

df['match_year'] = df['match_date'].dt.year
df['match_month'] = df['match_date'].dt.month
df['match_day_of_week'] = df['match_date'].dt.dayofweek
df['match_day_of_year'] = df['match_date'].dt.dayofyear

print("Nouvelles fonctionnalités temporelles ajoutées:")
display(df[['match_date', 'match_year', 'match_month', 'match_day_of_week', 'match_day_of_year']].head())

categorical_cols_to_encode = ['position', 'preferred_foot', 'tournament_stage', 'match_result']

df = pd.get_dummies(df, columns=categorical_cols_to_encode, drop_first=True)

print("Colonnes catégorielles encodées. Aperçu des nouvelles colonnes:")
print(df.filter(like='position_').columns)
print(df.filter(like='preferred_foot_').columns)
print(df.filter(like='tournament_stage_').columns)
print(df.filter(like='match_result_').columns)
print(f"\nNouvelles dimensions du DataFrame: {df.shape}")

columns_to_drop = [
    'successful_passes',
    'sprint_distance_km',
    'accelerations',
    'player_rating',
    'performance_score',
    'top_speed_kmh',
    'player_id',
    'player_name',
    'match_id'
]

df.drop(columns=columns_to_drop, errors='ignore', inplace=True)

print("Colonnes redondantes ou identifiants supprimés.")
print(f"\nNouvelles dimensions du DataFrame après suppression: {df.shape}")

print("\nInformation sur les types de données restants:")
df.info()

df.drop(columns=['match_date'], inplace=True)

print("Colonne 'match_date' supprimée.")
print(f"Nouvelles dimensions du DataFrame: {df.shape}")

categorical_cols_to_encode_final = ['stadium', 'city']

df = pd.get_dummies(df, columns=categorical_cols_to_encode_final, drop_first=True)

print("\nColonnes 'stadium' et 'city' encodées. Aperçu des nouvelles colonnes:")
print(df.filter(like='stadium_').columns)
print(df.filter(like='city_').columns)
print(f"\nDimensions finales du DataFrame après encodage: {df.shape}")

print("\nInformation sur les types de données restants:")
df.info()

remaining_categorical_cols = df.select_dtypes(include='object').columns

if not remaining_categorical_cols.empty:
    print("Colonnes catégorielles restantes (type 'object') et leurs valeurs uniques:")
    for col in remaining_categorical_cols:
        print(f"{col}: {df[col].nunique()} unique values")
    print("\nCes colonnes ont une cardinalité élevée. Leur traitement dépendra des objectifs spécifiques du modèle (par exemple, si on veut inclure l'identité des équipes ou des clubs) et des techniques d'encodage plus avancées, ou elles peuvent être exclues si leur information n'est pas jugée essentielle ou trop coûteuse à traiter.")
else:
    print("Toutes les colonnes catégorielles ont été encodées.")

high_cardinality_categorical_cols = ['nationality', 'team', 'club_name', 'opponent_team
df = pd.get_dummies(df, columns=high_cardinality_categorical_cols, drop_first=True)

print("Colonnes de haute cardinalité encodées.")
print(f"\nDimensions finales du DataFrame après encodage complet: {df.shape}")
print("\nInformation sur les types de données restants:")
df.info()

print("Jeu de données prêt pour la modélisation.")
print(f"Nombre final de lignes: {df.shape[0]}")
print(f"Nombre final de colonnes: {df.shape[1]}")

print("\nLes 5 premières lignes du DataFrame final:")
display(df.head())

high_cardinality_categorical_cols = ['nationality', 'team', 'club_name', 'opponent_team']
df = pd.get_dummies(df, columns=high_cardinality_categorical_cols, drop_first=True)

print("Colonnes de haute cardinalité encodées.")
print(f"\nDimensions finales du DataFrame après encodage complet: {df.shape}")
print("\nInformation sur les types de données restants:")
df.info()

print("Jeu de données prêt pour la modélisation.")
print(f"Nombre final de lignes: {df.shape[0]}")
print(f"Nombre final de colonnes: {df.shape[1]}")

print("\nLes 5 premières lignes du DataFrame final:")
display(df.head())

df.drop(columns=['match_date'], inplace=True)

print("Colonne 'match_date' supprimée.")
print(f"Nouvelles dimensions du DataFrame: {df.shape}")
categorical_cols_to_encode_final = ['stadium', 'city']
df = pd.get_dummies(df, columns=categorical_cols_to_encode_final, drop_first=True)

print("\nColonnes 'stadium' et 'city' encodées. Aperçu des nouvelles colonnes:")
print(df.filter(like='stadium_').columns)
print(df.filter(like='city_').columns)
print(f"\nDimensions finales du DataFrame après encodage: {df.shape}")

print("\nInformation sur les types de données restants:")
df.info()

remaining_categorical_cols = df.select_dtypes(include='object').columns

if not remaining_categorical_cols.empty:
    print("Colonnes catégorielles restantes (type 'object') et leurs valeurs uniques:")
    for col in remaining_categorical_cols:
        print(f"{col}: {df[col].nunique()} unique values")
    print("\nCes colonnes ont une cardinalité élevée et nécessitent des stratégies d'encodage plus avancées (par exemple, Target Encoding ou des méthodes basées sur les embeddings) si elles sont utilisées pour la modélisation, ou peuvent être exclues en fonction des objectifs du modèle.")
else:
    print("Toutes les colonnes catégorielles ont été encodées.")

high_cardinality_categorical_cols = ['nationality', 'team', 'club_name', 'opponent_team']

# Filter for columns that actually exist in the DataFrame
cols_to_encode_existing = [col for col in high_cardinality_categorical_cols if col in df.columns]

if cols_to_encode_existing:
    # Apply One-Hot Encoding only to existing columns
    df = pd.get_dummies(df, columns=cols_to_encode_existing, drop_first=True)
    print("Colonnes de haute cardinalité encodées.")
else:
    print("Les colonnes de haute cardinalité spécifiées n'existent plus dans le DataFrame (probablement déjà encodées).")

print(f"\nDimensions finales du DataFrame après encodage complet: {df.shape}")

# Display info to confirm no remaining object types (except for special cases if any)
print("\nInformation sur les types de données restants:")
df.info()

print("Jeu de données prêt pour la modélisation.")
print(f"Nombre final de lignes: {df.shape[0]}")
print(f"Nombre final de colonnes: {df.shape[1]}")

print("\nLes 5 premières lignes du DataFrame final:")
display(df.head())

bins = [-0.1, 5.0, 7.0, 9.1]
labels = ['Low', 'Medium', 'High']

df['tournament_rating_category'] = pd.cut(df['tournament_rating'], bins=bins, labels=labels, right=True)

print("Distribution de la nouvelle variable cible catégorielle:")
display(df['tournament_rating_category'].value_counts())

# Drop the original 'tournament_rating' column and convert target to numerical labels for scikit-learn
df.drop(columns=['tournament_rating'], inplace=True)

# Convert categorical labels to numerical for the classifier
df['tournament_rating_category_encoded'] = df['tournament_rating_category'].cat.codes
df.drop(columns=['tournament_rating_category'], inplace=True)

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
X = df.drop(columns=['tournament_rating_category_encoded'])
y = df['tournament_rating_category_encoded']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Taille de l'ensemble d'entraînement: {X_train.shape[0]} lignes")
print(f"Taille de l'ensemble de test: {X_test.shape[0]} lignes")

rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)

rf_classifier.fit(X_train, y_train)

print("Le classificateur Random Forest a été entraîné avec succès !")

from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

valid_indices_for_evaluation = y_test != -1

y_test_filtered = y_test[valid_indices_for_evaluation]
y_pred_filtered = y_pred[valid_indices_for_evaluation]

print("Rapport de Classification:")
print(classification_report(y_test_filtered, y_pred_filtered, target_names=['Low', 'Medium', 'High']))

cm = confusion_matrix(y_test_filtered, y_pred_filtered, labels=[0, 1, 2])

fig_cm = plt.figure(figsize=(8, 6))
display_cm = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Low', 'Medium', 'High'])
display_cm.plot(cmap=plt.cm.Blues)
plt.title('Matrice de Confusion')
plt.grid(False)
plt.show()

try:
    import imblearn
except ImportError:
    print("Installing imblearn...")
    !pip install imbalanced-learn
    import imblearn

from imblearn.over_sampling import SMOTE
from collections import Counter

print(f"Distribution des classes avant SMOTE: {Counter(y_train)}")

valid_train_indices = y_train != -1
X_train_filtered = X_train[valid_train_indices]
y_train_filtered = y_train[valid_train_indices]

sm = SMOTE(random_state=42, k_neighbors=1)
X_train_res, y_train_res = sm.fit_resample(X_train_filtered, y_train_filtered)

print(f"Distribution des classes après SMOTE: {Counter(y_train_res)}")

try:
    import imblearn
except ImportError:
    print("Installing imblearn...")
    !pip install imbalanced-learn
    import imblearn

from imblearn.over_sampling import SMOTE
from collections import Counter

print(f"Distribution des classes avant SMOTE: {Counter(y_train)}")

valid_train_indices = y_train != -1
X_train_filtered = X_train[valid_train_indices]
y_train_filtered = y_train[valid_train_indices]

sm = SMOTE(random_state=42, k_neighbors=1)
X_train_res, y_train_res = sm.fit_resample(X_train_filtered, y_train_filtered)

print(f"Distribution des classes après SMOTE: {Counter(y_train_res)}")

print(f"Distribution des classes après SMOTE: {Counter(y_train_res)}")

from sklearn.ensemble import RandomForestClassifier

rf_classifier_smote = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
rf_classifier_smote.fit(X_train_res, y_train_res)

print("Le classificateur Random Forest a été ré-entraîné avec succès sur les données équilibrées par SMOTE !")

print("Le classificateur Random Forest a été ré-entraîné avec succès sur les données équilibrées par SMOTE !")

"""### Ré-évaluation du Classificateur Random Forest après SMOTE

Nous allons maintenant ré-évaluer les performances du modèle sur l'ensemble de test (qui n'a pas été modifié) pour observer l'impact de l'application de SMOTE sur la détection de la catégorie `High`.
"""

from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

y_pred_smote = rf_classifier_smote.predict(X_test)

valid_indices_for_evaluation = y_test != -1

y_test_filtered = y_test[valid_indices_for_evaluation]
y_pred_smote_filtered = y_pred_smote[valid_indices_for_evaluation]

print("Rapport de Classification (après SMOTE):")
print(classification_report(y_test_filtered, y_pred_smote_filtered, target_names=['Low', 'Medium', 'High']))

# Compute and plot the confusion matrix for the filtered data and the 3 expected classes
cm_smote = confusion_matrix(y_test_filtered, y_pred_smote_filtered, labels=[0, 1, 2])

fig_cm_smote = plt.figure(figsize=(8, 6))
display_cm_smote = ConfusionMatrixDisplay(confusion_matrix=cm_smote, display_labels=['Low', 'Medium', 'High'])
display_cm_smote.plot(cmap=plt.cm.Blues)
plt.title('Matrice de Confusion (après SMOTE)')
plt.grid(False)
plt.show()