# -*- coding: utf-8 -*-
"""madagascar_health_facilities

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wnL1VcQ_CgYQafdcdiV0skqJ5Qh-00LK

## README: Analyse des Établissements de Santé à Madagascar

Ce notebook contient une analyse exploratoire des données des établissements de santé à Madagascar, chargées à partir d'un fichier GeoJSON.

### Aperçu de l'Analyse :

1.  **Chargement et Exploration des Données** : Les données ont été chargées à l'aide de `pandas_geojson` et un aperçu initial a été effectué pour comprendre la structure et les types de colonnes.
2.  **Visualisation Géospatiale** : Une carte interactive (`folium`) a été générée pour visualiser la répartition géographique des établissements de santé à travers Madagascar.
3.  **Distribution des Types d'Aménités** : L'analyse a examiné la fréquence des différents types d'aménités (hôpitaux, cliniques, pharmacies, etc.) pour comprendre la typologie des installations disponibles.
4.  **Analyse de Capacité** : Une tentative d'analyse de la capacité des installations (nombre de lits, de médecins, d'infirmiers) a été effectuée. Cependant, il a été constaté que ces colonnes contenaient un grand nombre de valeurs manquantes ou nulles, limitant la profondeur de cette analyse.
5.  **Distribution de l'Eau et de l'Électricité** : La disponibilité de l'eau et de l'électricité a été analysée à l'aide de la colonne `properties.water_source` et `properties.electricity`.
6.  **Scores de Complétude et Tendances de Mise à Jour** : Les scores de complétude des données et les tendances de mise à jour au fil des ans ont été examinés.
7.  **Matrice de Corrélation** : Une matrice de corrélation a été calculée pour identifier les relations entre les variables numériques.

### Conclusion sur la Prédiction de l'Accès à l'Électricité et à l'Eau :

**Il est quasi impossible de réaliser des prédictions fiables sur l'accès à l'électricité et à l'eau d'un établissement de santé en fonction de sa localisation, de sa région sanitaire et de sa typologie.**

Cette limitation est principalement due à l'**insuffisance de données** dans les colonnes `properties.electricity` et `properties.water_source`. Malgré les efforts de nettoyage et de catégorisation, un pourcentage significatif de ces informations est soit manquant, soit catégorisé comme 'Not specified' ou 'Other / Specified', ce qui ne permet pas d'établir des modèles prédictifs robustes. Pour des analyses plus approfondies ou des prédictions, il serait essentiel d'enrichir ces colonnes avec des données plus complètes et granulaires.
"""

import pandas_geojson as pdg
import pandas as pd
geojson = pdg.read_geojson('madagascar.geojson')
df = geojson.to_dataframe()
df.head()

df.shape
df.describe()

df_min = df.drop(columns=['properties.uuid', 'properties.addr_postcode', 'properties.addr_housenumber', 'properties.addr_street', 'properties.addr_city'])
df_min.shape
df_min

for col in df_min.columns:
  print(df_min[col].notna().any())

df.columns

import folium

# Helper function to safely extract coordinates
def get_coord(coord_list, index):
    if isinstance(coord_list, list) and len(coord_list) > index:
        return coord_list[index]
    return None

df_min['longitude'] = df_min['geometry.coordinates'].apply(lambda x: get_coord(x, 0))
df_min['latitude'] = df_min['geometry.coordinates'].apply(lambda x: get_coord(x, 1))

# Convert to numeric, coercing errors to NaN
df_min['longitude'] = pd.to_numeric(df_min['longitude'], errors='coerce')
df_min['latitude'] = pd.to_numeric(df_min['latitude'], errors='coerce')

# Drop rows with NaN coordinates if any
df_min.dropna(subset=['latitude', 'longitude'], inplace=True)

# Get the mean coordinates to center the map (Madagascar is around -18.9 latitude, 47.5 longitude)
map_center = [df_min['latitude'].mean(), df_min['longitude'].mean()]

# Create a folium map
m = folium.Map(location=map_center, zoom_start=6)

# Add markers for each healthcare facility
for idx, row in df_min.iterrows():
    # Use 'properties.name' if available, otherwise use 'properties.amenity' or a generic name
    popup_text = f"<b>Name:</b> {row['properties.name']}<br><b>Type:</b> {row['properties.amenity'] or row['properties.healthcare']}"
    folium.Marker(
        location=[row['latitude'], row['longitude']],
        popup=popup_text,
        tooltip=row['properties.name'] or 'Healthcare Facility'
    ).add_to(m)

# Display the map
m

import matplotlib.pyplot as plt
import seaborn as sns

# Count the occurrences of each amenity type
amenity_counts = df['properties.amenity'].value_counts().reset_index()
amenity_counts.columns = ['Amenity Type', 'Count']

# Create the bar chart
plt.figure(figsize=(12, 7))
sns.barplot(x='Amenity Type', y='Count', data=amenity_counts, palette='viridis', hue='Amenity Type', legend=False)
plt.title('Distribution of Healthcare Facilities by Amenity Type')
plt.xlabel('Amenity Type')
plt.ylabel('Number of Facilities')
plt.xticks(rotation=45, ha='right') # Rotate labels for better readability
plt.tight_layout()
plt.show()

df['facility_type'] = df['properties.amenity'].fillna("Unknown").str.lower().str.strip()
counts = df['facility_type'].value_counts()
percentages = counts / counts.sum() * 100
print(percentages)
df_typology = pd.DataFrame({'Count': counts, 'percentage': percentages.values})
df_typology.head()

from numpy._core.fromnumeric import mean
df['properties.beds'] = pd.to_numeric(df['properties.beds'], errors='coerce')
df['properties.beds'] = df['properties.beds'].fillna(0)
df['properties.staff_doctors'] = pd.to_numeric(df['properties.staff_doctors'], errors='coerce')
df['properties.staff_doctors'] = df['properties.staff_doctors'].fillna(0)
df['properties.staff_nurses'] = pd.to_numeric(df['properties.staff_nurses'], errors='coerce')
df['properties.staff_nurses'] = df['properties.staff_nurses'].fillna(0)
total_beds = int(df['properties.beds'].sum())
total_doctors = int(df['properties.staff_doctors'].sum())
total_nurses = int(df['properties.staff_nurses'].sum())
capacity_analysis = df.groupby('facility_type').agg(
    facility_count=('facility_type', 'count'),
    total_beds=('properties.beds', 'sum'),
    total_doctors=('properties.staff_doctors', 'sum'),
    total_nurses=('properties.staff_nurses', 'sum'),
    mean_beds=('properties.beds', 'mean'),
    mean_doctors=('properties.staff_doctors', 'mean'),
    mean_nurses=('properties.staff_nurses', 'mean')
).round(1)
capacity_analysis_graph = capacity_analysis[capacity_analysis['total_beds']>0].sort_values(by='total_beds', ascending=False)
if not capacity_analysis_graph.empty:
    plt.figure(figsize=(8, 6))
    sns.set_theme(style="whitegrid")
    sns.barplot(x=capacity_analysis_graph['total_beds'], y=capacity_analysis_graph.index, data=capacity_analysis_graph, palette='flare')
    plt.title('Facility Capacity Analysis')
    plt.xlabel('Total Beds')
    plt.ylabel('Facility Type')
    plt.grid(axis='x', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()
else:
    print("No data available for analysis.")

capacity_analysis.head()

df['properties.electricity'] = df['properties.electricity'].fillna("Not specified").str.lower().str.strip()
df['properties.water_source'] = df['properties.water_source'].fillna("Not specified").str.lower().str.strip()
simplified_mapping = {
    'yes': 'Available',
    'no': 'Not available',
    'grid': 'National network',
    'generator': 'Generator',
    'solar': 'Solar',
    'none': 'Not available',
    'not specified': 'Not specified'
}
def simplify_status(value):
    value_lower = str(value).lower().strip()

    # Prioritize specific sources for electricity
    if 'grid' in value_lower or 'national' in value_lower or 'utility' in value_lower or 'public' in value_lower or 'jiny' in value_lower or 'main' in value_lower or 'hydro' in value_lower:
        return 'National network'
    if 'generator' in value_lower or 'gen' in value_lower or 'battery' in value_lower:
        return 'Generator'
    if 'solar' in value_lower or 'photovoltaic' in value_lower:
        return 'Solar'

    # Prioritize specific sources for water
    if 'tap' in value_lower or 'pipe' in value_lower or 'faucet' in value_lower:
        return 'Tap water'
    if 'well' in value_lower:
        return 'Well'
    if 'borehole' in value_lower or 'forage' in value_lower:
        return 'Borehole'
    if 'communal' in value_lower or 'pump' in value_lower:
        return 'Communal pump'
        return 'Natural source'

    # Then general availability
    if 'yes' in value_lower or 'available' in value_lower or 'present' in value_lower:
        return 'Available'
    if 'none' in value_lower or 'no' in value_lower or 'n/a' in value_lower or 'not available' in value_lower or 'absent' in value_lower:
        return 'Not available'

    # Finally, handle unspecified/empty values
    if not value_lower or value_lower == 'not specified' or 'unspecified' in value_lower or 'unknown' in value_lower or 'inconnu' in value_lower:
        return 'Not specified'

    return 'Other / Specified' # Catch-all for anything else that didn't match
df['statu_elec'] = df['properties.electricity'].apply(simplify_status)
df['statu_water'] = df['properties.water_source'].apply(simplify_status)
water_counts = df['statu_water'].value_counts()
elec_counts = df['statu_elec'].value_counts()
water_percentages = water_counts / water_counts.sum() * 100
elec_percentages = elec_counts / elec_counts.sum() * 100
df_water = pd.DataFrame({'Count': water_counts, 'percentage': water_percentages.values})
df_elec = pd.DataFrame({'Count': elec_counts, 'percentage': elec_percentages.values})
df_water_elec = pd.concat([df_water, df_elec], axis=1)
df_water_elec.columns = ['Count_water', 'percentage_water', 'Count_elec', 'percentage_elec']
df_water_elec
sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(1,2, figsize=(12, 6))
sns.barplot(x=df_water['Count'], y=df_water.index, ax=axes[0], palette='Blues', hue=df_water.index, legend=False)
sns.barplot(x=df_elec['Count'], y=df_elec.index, ax=axes[1], palette='Reds', hue=df_elec.index, legend=False)
axes[0].set_title('Distribution of Water Facilities')
axes[0].set_xlabel('Water Status')
axes[0].set_ylabel('Number of Facilities')
axes[0].grid(axis='y', linestyle='--', alpha=0.7)
axes[1].set_title('Distribution of Electricity Facilities')
axes[1].set_xlabel('Electricity Status')
axes[1].set_ylabel('Number of Facilities')
for i, p in enumerate(axes[0].patches):
    width = p.get_width()
    axes[0].text(width + 1, p.get_y() + p.get_height() / 2, f'{water_percentages.iloc[i]:.1f}%', va='center')
for i, p in enumerate(axes[1].patches):
    width = p.get_width()
    axes[1].text(width + 1, p.get_y() + p.get_height() / 2, f'{elec_percentages.iloc[i]:.1f}%', va='center')
plt.suptitle("Distribution of Water and electricity in health centers in Madagascar", fontweight="bold", fontsize=16, y=1.02)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.histplot(df_min['properties.completeness'], kde=True, bins=20)
plt.title('Distribution of Facility Completeness Scores')
plt.xlabel('Completeness Score')
plt.ylabel('Number of Facilities')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

df_min['properties.changeset_timestamp'] = pd.to_datetime(df_min['properties.changeset_timestamp'])
df_min['update_year'] = df_min['properties.changeset_timestamp'].dt.year

# Display the count of updates per year
update_trends = df_min['update_year'].value_counts().sort_index()
display(update_trends)

plt.figure(figsize=(12, 6))
sns.barplot(x=update_trends.index, y=update_trends.values, palette='viridis', hue=update_trends.index, legend=False)
plt.title('Number of Facility Updates by Year')
plt.xlabel('Year')
plt.ylabel('Number of Updates')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

df_min['properties.completeness'].describe()

import numpy as np



dfmin_num = df_min.select_dtypes(include=['number'])

corr_matrix = dfmin_num.corr()

plt.figure(figsize=(8, 6))


# 6. Génération de la Heatmap Seaborn
sns.heatmap(
    corr_matrix,
    annot=True,
    cmap='coolwarm',
    fmt=".2f",
    vmin=-1, vmax=1,
    square=True,
    linewidths=0.5,
    cbar_kws={"shrink": 0.8}
)

# 7. Personnalisation du titre et affichage
plt.title('Matrice de Corrélation des Variables', fontsize=14, pad=15)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

changeset_version = df['properties.changeset_version'].value_counts().reset_index()
changeset_version.columns = ['Changeset_version', 'Count']
sns.barplot(x='Changeset_version', y='Count', hue='Changeset_version', data=changeset_version, palette='viridis', legend=False)
plt.title('Distribution of Changeset Versions')
plt.xlabel('Changeset Version')
plt.ylabel('Number of Facilities')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

def encode_target(value):
  if pd.isna(value):
    return None
  str_value = str(value).lower().strip()
  if str_value in ['no', 'none', 'not specified']:
    return 0
  elif str_value in ['yes', 'grid', 'solar', 'generator', 'available']:
    return 1
  return None

df['target_elec'] = df['properties.electricity'].apply(encode_target)
df_model = df[df['target_elec'].notna()].copy()
print(f'Data available for training:{len(df_model)}')

def extract_lat_lon(coord_list):
  if isinstance(coord_list, list) and len(coord_list) >= 2:
    # geojson coordinates are typically [longitude, latitude]
    return coord_list[1], coord_list[0] # Return (latitude, longitude)
  return np.nan, np.nan # Return (NaN, NaN)
df_model[['latitude', 'longitude']] = df_model['geometry.coordinates'].apply(lambda x: pd.Series(extract_lat_lon(x)))
df_model['longitude'] = df_model['longitude'].fillna(df_model['longitude'].median())
df_model['latitude'] = df_model['latitude'].fillna(df_model['latitude'].median())

df_model['properties.amenity'] = df_model['properties.amenity'].fillna('unknown')
df_model['properties.is_in_health_zone'] = df_model['properties.is_in_health_zone'].fillna('unknown')

categorical_features = ['properties.amenity', 'properties.is_in_health_zone']
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoded_features = encoder.fit_transform(df_model[categorical_features])

Xnum = df_model[['longitude', 'latitude']].values
X = np.hstack((Xnum, encoded_features))
y = df_model['target_elec'].astype(int).values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

unique_classes_in_test = np.unique(y_test)
if len(unique_classes_in_test) < 2:
    print(f"Warning: Only {len(unique_classes_in_test)} unique class(es) found in the test set ({unique_classes_in_test}).")
    print("A full classification report cannot be generated as it requires at least two classes for comparison.")
    print("This confirms the severe data insufficiency for binary classification that was previously noted, as the target variable 'target_elec' contains only one class (all 'Has elec') in the entire modeling dataset.")
    print("\nConfusion Matrix (for the single class present):")
    print(confusion_matrix(y_test, y_pred))
else:
    print(classification_report(y_test, y_pred, target_names=['Has elec', 'No elec']))
    print(confusion_matrix(y_test, y_pred))



import matplotlib.pyplot as plt
import seaborn as sns

# Count the occurrences of each unique value in 'target_elec', including NaN
elec_target_distribution = df['target_elec'].value_counts(dropna=False).sort_index()

# Map numerical values to descriptive labels for better readability
labels = elec_target_distribution.index.map({0.0: 'No Electricity', 1.0: 'Has Electricity', np.nan: 'Not Specified'}).fillna('Not Specified')

plt.figure(figsize=(8, 5))
sns.barplot(x=labels, y=elec_target_distribution.values, palette='viridis', hue=labels, legend=False)
plt.title('Distribution of Electricity Access (target_elec)')
plt.xlabel('Electricity Status')
plt.ylabel('Number of Facilities')
plt.xticks(rotation=45, ha='right')

# Add percentage labels on top of bars
total = elec_target_distribution.sum()
for index, value in enumerate(elec_target_distribution.values):
    percentage = f'{(value / total) * 100:.2f}%'
    plt.text(index, value + (total * 0.01), percentage, ha='center', va='bottom') # Adjust offset for better visibility

plt.tight_layout()
plt.show()