# -*- coding: utf-8 -*-
"""OFFRE D'EMPLOIS(ASAKO.MG) ANALYSE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sOXXLII_ullwF9p7w5BOmJHaHVYbfIAq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
sns.set_palette("muted")
sns.set_style("darkgrid")

df = pd.read_csv("offres_d_emplois.csv")
print(f"Dataframe shape:\n{df.shape}")
print(f"Dataframe columns:\n{df.columns}")
df.head()
print(f"Dataframe info:\n{df.info()}")
df.describe()

# NaN count and Nan percentage
Valeurs_manquantes = df.isnull().sum()
Valeurs_manquantes_percent = 100*df.isnull().sum()/len(df)
print(Valeurs_manquantes)
print(Valeurs_manquantes_percent)
missing_data = pd.DataFrame({'Valeurs_manquantes': Valeurs_manquantes, 'Valeurs_manquantes_percent': Valeurs_manquantes_percent})
missing_data

df.drop(columns=['web_scraper_order'], inplace=True)

df.rename(columns={'web_scraper_start_url':'URL source'})

df.head()

contrat_counts = df['Contrat'].value_counts()
colors = sns.color_palette("deep")

plt.figure(figsize=(7, 7))
plt.pie(
    contrat_counts,
    labels=contrat_counts.index,
    autopct='%1.1f%%',
    startangle=140,
    colors=colors
)
plt.title("Répartition des types de contrats")
plt.show()

domaine_counts = df["Domaine d'activité"].value_counts().sort_values(ascending=False)
plt.figure(figsize=(10, 6))
plt.bar(domaine_counts.index, domaine_counts.values)
plt.xlabel("Domaine d'activité")
plt.ylabel("Nombre d'offres d'emploi")
plt.title("Répartition des offres par domaine d'activité")
plt.xticks(rotation=45, ha='right')
plt.show()

poste_counts = df['Poste'].value_counts().sort_values(ascending=False).nlargest(20)
plt.figure(figsize=(12, 8))
plt.barh(poste_counts.index, poste_counts.values)
plt.xlabel("Nombre d'offres d'emploi")
plt.ylabel("Poste")
plt.title("Répartition des postes")
plt.show()

localisation_counts = df['Localisation'].value_counts().sort_values(ascending=False)
colors = sns.color_palette("muted")
plt.figure(figsize=(8, 6))

plt.pie(
    localisation_counts,
    labels=None,
    autopct=None,
    startangle=140,
    colors=colors,
    pctdistance=0.75
)

plt.legend(
    labels=localisation_counts.index,
    title="Localisations",
    loc="center left",
    bbox_to_anchor=(1, 0, 0.5, 1)
)

plt.title("Répartition des offres selon la localisation")
plt.tight_layout()
plt.show()

societee_counts = df['Nom de la société'].value_counts().sort_values(ascending=False).nlargest(10)
plt.figure(figsize=(10, 6))
plt.bar(societee_counts.index, societee_counts.values)
plt.xlabel("Nom des sociétés")
plt.ylabel("Nombre d'offres d'emplois")
plt.title("Les 10 entreprises leaders en volume de recrutement")
plt.xticks(rotation=45, ha='right')
plt.show()

"""## README: Analyse des Offres d'Emploi sur Asako.mg

### Introduction
Ce notebook contient une analyse exploratoire des offres d'emploi collectées à partir du site web asako.mg. L'objectif est de comprendre la distribution des types de contrats, les domaines d'activité dominants, les postes les plus recherchés, les localisations géographiques des offres, et les entreprises qui recrutent le plus.

### Aperçu des Données
Le jeu de données, `offres_d_emplois.csv`, contient 201 entrées et 7 colonnes initiales. Chaque entrée représente une offre d'emploi. Les colonnes incluent des informations telles que le poste, le nom de la société, la localisation, le domaine d'activité et le type de contrat.

**Colonnes Initiales**:
* `web_scraper_order`: Identifiant unique du scraping.
* `web_scraper_start_url`: URL source du scraping.
* `Poste`: Titre du poste.
* `Nom de la société`: Nom de l'entreprise qui recrute.
* `Localisation`: Lieu de l'emploi.
* `Domaine d'activité`: Secteur d'activité de l'emploi.
* `Contrat`: Type de contrat (CDI, CDD, Freelance, Stage).

### Nettoyage et Préparation des Données
1.  **Vérification des Valeurs Manquantes**: Aucune valeur manquante n'a été détectée dans le jeu de données, ce qui simplifie l'étape de nettoyage.
2.  **Suppression de Colonnes Inutiles**: La colonne `web_scraper_order` a été supprimée car elle n'apportait pas d'informations pertinentes pour l'analyse.
3.  **Renommage de Colonnes**: La colonne `web_scraper_start_url` a été renommée en `URL source` pour une meilleure lisibilité (cette modification n'a pas été appliquée au DataFrame `df` directement dans le notebook, mais elle est pertinente pour la compréhension conceptuelle).

### Analyse Exploratoire des Données et Visualisations
Plusieurs visualisations ont été générées pour explorer les distributions et les tendances:

1.  **Répartition des Types de Contrats**: Un diagramme circulaire montre que les contrats à durée indéterminée (CDI) dominent largement le marché avec 74.1% des offres, suivis par les contrats Freelance (18.4%), CDD (5.0%) et Stage (2.5%).

2.  **Répartition des Offres par Domaine d'Activité**: Un graphique à barres indique que les "Centres d'appels & BPO" et le "Commerce & Vente" sont les domaines d'activité qui génèrent le plus grand nombre d'offres d'emploi. Ce qui suggère une forte demande dans ces secteurs.

3.  **Répartition des Postes les plus Fréquents**: Un graphique à barres horizontales affiche les 20 postes les plus offerts. "Agent de Chat" est de loin le poste le plus recherché, suivi par "Chauffeur". Cela met en évidence la forte demande pour des rôles spécifiques souvent associés aux centres d'appels et à la logistique.

4.  **Répartition des Offres par Localisation**: Un diagramme circulaire montre qu'"Antananarivo" est le principal pôle d'emploi, représentant la majorité des offres. Les emplois "Remote · Madagascar" constituent la deuxième catégorie la plus importante, soulignant la présence d'opportunités de travail à distance.

5.  **Les 10 Entreprises Leaders en Volume de Recrutement**: Un graphique à barres identifie les entreprises qui publient le plus grand nombre d'offres. "GROUPE ALTHEA" et "LearnProgress" sont en tête, indiquant qu'elles sont des acteurs majeurs du recrutement sur asako.mg.

### Conclusions
*   **Prédominance du CDI**: Le marché de l'emploi sur asako.mg est fortement axé sur les contrats à durée indéterminée, ce qui peut rassurer les candidats à la recherche de stabilité.
*   **Secteurs Porteurs**: Les secteurs des Centres d'appels/BPO et du Commerce/Vente sont les plus dynamiques en termes d'offres d'emploi, en particulier pour des postes comme "Agent de Chat".
*   **Concentration Géographique**: Antananarivo reste le centre névralgique de l'emploi, mais les opportunités en télétravail ("Remote · Madagascar") sont également significatives, offrant de la flexibilité.
*   **Acteurs Clés du Recrutement**: Quelques entreprises dominent le volume de recrutement, ce qui pourrait être un point de départ pour les candidats ciblant ces employeurs.

Cette analyse fournit un aperçu clair des tendances du marché de l'emploi tel que reflété par les données d'asako.mg, aidant potentiellement les chercheurs d'emploi à cibler leurs recherches et les recruteurs à comprendre le paysage concurrentiel.
"""