# -*- coding: utf-8 -*-
"""VOLS DEPUIS TANA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J4riAefbs4ZgOojHuPwmXLoYESMzHQPz

# Analyse des Données de Vols Google Flights

## Aperçu du Projet
Ce projet a pour objectif d'analyser les données de vols collectées à partir de Google Flights pour comprendre les différents facteurs influençant les prix, les durées et le nombre d'escales des vols **au départ d'Antananarivo, Madagascar**. L'analyse implique le nettoyage et la combinaison de données provenant de multiples sources, la transformation des caractéristiques pertinentes en formats numériques et la visualisation des corrélations et des distributions pour dégager des informations clés.

## Sources de Données
L'analyse utilise trois fichiers CSV, chacun contenant des informations de vol:
*   `google_flights.csv`: Jeu de données principal.
*   `google_flights_usa.csv`: Données supplémentaires pour les vols vers/depuis les États-Unis.
*   `google_flights_asia.csv`: Données supplémentaires pour les vols vers/depuis l'Asie.

## Étapes de l'Analyse
1.  **Chargement des Données et Nettoyage Initial**: Chargement des jeux de données bruts et réalisation du renommage initial des colonnes et du nettoyage des URL.
2.  **Combinaison des DataFrames**: Fusion des trois DataFrames individuels en un seul jeu de données complet.
3.  **Nettoyage et Conversion des Colonnes Numériques**: Conversion des colonnes 'Prix du vol', 'Durée du vol' et 'Escales' en formats numériques pour une analyse quantitative.
4.  **Analyse Exploratoire des Données (AED)**:
    *   Visualisation des distributions des variables numériques clés (prix, durée, escales).
    *   Analyse de la corrélation entre la durée du vol et le prix.
    *   Identification des vols les plus et les moins chers.
    *   Visualisation de la matrice de corrélation entre toutes les colonnes numériques à l'aide d'une carte de chaleur (heatmap).
    *   Examen de l'impact du nombre d'escales sur les prix des vols à l'aide de diagrammes en boîte (box plots).

## Principales Conclusions
*   **Faible Corrélation entre Durée et Prix**: Une très faible corrélation négative a été observée entre la durée du vol et le prix, suggérant que les vols plus longs ne sont pas nécessairement plus chers, et peuvent parfois être moins chers.
*   **Corrélation entre Durée et Escales**: Une corrélation positive modérée existe entre la durée du vol et le nombre d'escales, ce qui est attendu car plus d'escales entraînent généralement des temps de trajet plus longs.
*   **Impact des Escales sur le Prix**: Les vols avec plus d'escales ont généralement tendance à être plus chers, bien qu'il y ait une variabilité significative au sein de chaque catégorie d'escales.

## Configuration
Pour exécuter ce notebook, vous aurez besoin de Python et des bibliothèques suivantes:
*   `pandas`
*   `numpy`
*   `matplotlib`
*   `seaborn`

Celles-ci peuvent généralement être installées via pip:
```bash
pip install pandas numpy matplotlib seaborn
```
"""

import pandas as pd
df = pd.read_csv("google_flights.csv")
df.drop(columns='web_scraper_order', inplace=True)
df.columns = ['URL source', 'Destination', 'Période de voyage', 'Durée du vol', 'Prix du vol', 'Escales']
df.head()

import re

def extract_domain(url):
    url = re.sub(r'https?://(?:www\.)?', '', url)
    match = re.match(r'([^/]+)', url)
    if match:
        return match.group(1)
    return url

df['URL source'] = df['URL source'].apply(extract_domain)


display(df.head())

df2 = pd.read_csv("google_flights_asia.csv")

# Remplacer les valeurs manquantes dans la colonne 'data6' par 'Indisponible'
df2['data6'].fillna('Indisponible', inplace=True)

df2.head()

"""### Nouvelle fonction de nettoyage d'URL et combinaison des DataFrames

Je vais définir une nouvelle fonction pour nettoyer la colonne `URL source` en supprimant uniquement les préfixes `http(s)://` et `www.`, tout en conservant le chemin de l'URL. Ensuite, je vais recharger les DataFrames, appliquer cette fonction et uniformiser les noms de colonnes avant de les combiner.
"""

import re
import numpy as np # Import numpy for NaN

def clean_url_prefix(url):
    if pd.isna(url):
        return url
    # Remove 'https://www.' or 'http://www.' or 'https://' or 'http://'
    cleaned_url = re.sub(r'https?://(?:www\.)?', '', str(url))
    return cleaned_url

# --- Traitement du DataFrame df (google_flights.csv) ---
df = pd.read_csv("google_flights.csv")
df.drop(columns='web_scraper_order', inplace=True)
df.columns = ['URL source', 'Destination', 'Période de voyage', 'Durée du vol', 'Prix du vol', 'Escales']
df['URL source'] = df['URL source'].apply(clean_url_prefix)
print("df traité:")
display(df.head())

# --- Traitement du DataFrame df1 (google_flights_usa.csv) ---
df1 = pd.read_csv("google_flights_usa.csv")
df1['web_scraper_start_url'] = df1['web_scraper_start_url'].apply(clean_url_prefix)

df1_to_drop = ['web_scraper_order', 'data3']
existing_df1_to_drop = [col for col in df1_to_drop if col in df1.columns]
df1.drop(columns=existing_df1_to_drop, inplace=True)

df1.rename(columns={
    'web_scraper_start_url': 'URL source',
    'data': 'Destination',
    'data4': 'Durée du vol',
    'data2': 'Prix du vol',
    'data5': 'Escales'
}, inplace=True)

df1['Période de voyage'] = np.nan

df1 = df1[df.columns]

print("\ndf1 traité:")
display(df1.head())

# --- Traitement du DataFrame df2 (google_flights_asia.csv) ---
df2 = pd.read_csv("google_flights_asia.csv")
df2['web_scraper_start_url'] = df2['web_scraper_start_url'].apply(clean_url_prefix)

df2_to_drop = ['web_scraper_order', 'data3', 'data5']
existing_df2_to_drop = [col for col in df2_to_drop if col in df2.columns]
df2.drop(columns=existing_df2_to_drop, inplace=True)

df2.rename(columns={
    'web_scraper_start_url': 'URL source',
    'data': 'Destination',
    'data4': 'Durée du vol',
    'data2': 'Prix du vol',
    'data6': 'Escales'
}, inplace=True)

df2['Période de voyage'] = np.nan

df2 = df2[df.columns]

print("\ndf2 traité:")
display(df2.head())

"""### Combinaison des DataFrames"""

# Concaténer les trois DataFrames
combined_df = pd.concat([df, df1, df2], ignore_index=True)

print("DataFrame combiné (premières lignes):")
display(combined_df.head())

print("\nInformations sur le DataFrame combiné:")
combined_df.info()

import re

def get_currency_type(price_str):
    if pd.isna(price_str):
        return None
    s = str(price_str)
    if 'MGA' in s:
        return 'MGA'
    elif '€' in s:
        return 'EUR'
    return None

combined_df['Currency'] = combined_df['Prix du vol'].apply(get_currency_type)
print("DataFrame combiné avec la colonne 'Currency':")
display(combined_df.head())

import matplotlib.ticker as mticker

def format_mga(x, pos):
    if x >= 1_000_000:
        return f'{x/1_000_000:.1f}M Ar'
    elif x >= 1_000:
        return f'{x/1_000:.1f}K Ar'
    return f'{int(x)} Ar'

def format_eur(x, pos):
    if x >= 1_000_000:
        return f'{x/1_000_000:.1f}M €'
    elif x >= 1_000:
        return f'{x/1_000:.1f}K €'
    return f'{int(x)} €'

mga_formatter = mticker.FuncFormatter(format_mga)
eur_formatter = mticker.FuncFormatter(format_eur)

print("Fonctions de formatage de devise définies.")

"""### Nettoyage et conversion des colonnes numériques pour l'analyse"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

# Fonction de nettoyage et conversion pour 'Prix du vol'
def clean_price(price_str):
    if pd.isna(price_str):
        return np.nan
    s = str(price_str).strip()
    s = s.replace(' MGA', '').replace(' €', '').replace(' ', '').replace('\xa0', '')

    match = re.search(r'(\d+[ .\s]?\d*[,.]?\d*)', s)
    if match:
        num_str = match.group(1)
        num_str = num_str.replace('.', '').replace(' ', '')
        num_str = num_str.replace(',', '.')
        try:
            return float(num_str)
        except ValueError:
            return np.nan
    return np.nan

def clean_duration(duration_str):
    if pd.isna(duration_str):
        return np.nan
    total_minutes = 0
    duration_str = str(duration_str).replace('\xa0', ' ')
    parts = duration_str.split(' ')

    if 'h' in parts:
        try:
            h_index = parts.index('h')
            total_minutes += int(parts[h_index - 1]) * 60
        except (ValueError, IndexError):
            pass

    if 'min' in parts:
        try:
            min_index = parts.index('min')
            total_minutes += int(parts[min_index - 1])
        except (ValueError, IndexError):
            pass

    if total_minutes == 0 and len(parts) == 1 and parts[0].isdigit():
        try:
            total_minutes = int(parts[0]) * 60
        except ValueError:
            pass

    if total_minutes == 0 and ('h' not in parts) and ('min' not in parts):
        return np.nan

    return total_minutes


# Appliquer les fonctions de nettoyage
combined_df['Prix du vol (numérique)'] = combined_df['Prix du vol'].apply(clean_price)
combined_df['Durée du vol (minutes)'] = combined_df['Durée du vol'].apply(clean_duration)

# Convertir 'Escales' en numérique, en traitant 'Indisponible' comme NaN si nécessaire
def clean_escales(escales_str):
    if pd.isna(escales_str) or str(escales_str).lower() == 'indisponible':
        return np.nan
    s = str(escales_str).lower()
    if 'sans escale' in s or 'direct' in s or '0 escale' in s:
        return 0
    try:
        match = re.search(r'(\d+)\s*escale', s)
        if match:
            return int(match.group(1))
        return np.nan
    except ValueError:
        return np.nan

combined_df['Nombre d\'escales'] = combined_df['Escales'].apply(clean_escales)

print("Descriptive statistics for cleaned numerical columns:")
display(combined_df[['Prix du vol (numérique)', 'Durée du vol (minutes)', 'Nombre d\'escales']].describe())

"""### Visualisation de la distribution des Prix du vol, Durées du vol et Nombre d'escales"""

# Filter data by currency
df_mga = combined_df[combined_df['Currency'] == 'MGA'].dropna(subset=['Prix du vol (numérique)'])
df_eur = combined_df[combined_df['Currency'] == 'EUR'].dropna(subset=['Prix du vol (numérique)'])

# Distribution des Prix du vol (MGA)
if not df_mga.empty:
    plt.figure(figsize=(9, 6))
    sns.histplot(df_mga['Prix du vol (numérique)'], kde=True)
    plt.title('Distribution des Prix du vol (MGA)')
    plt.xlabel('Prix du vol (MGA)')
    plt.ylabel('Fréquence')
    plt.gca().xaxis.set_major_formatter(mga_formatter)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()
else:
    print("Aucune donnée MGA à afficher pour la distribution des prix.")

# Distribution des Prix du vol (EUR)
if not df_eur.empty:
    plt.figure(figsize=(9, 6))
    sns.histplot(df_eur['Prix du vol (numérique)'], kde=True)
    plt.title('Distribution des Prix du vol (EUR)')
    plt.xlabel('Prix du vol (EUR)')
    plt.ylabel('Fréquence')
    plt.gca().xaxis.set_major_formatter(eur_formatter)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()
else:
    print("Aucune donnée EUR à afficher pour la distribution des prix.")

plt.figure(figsize=(9, 6))
sns.histplot(combined_df['Durée du vol (minutes)'].dropna(), kde=True)
plt.title('Distribution des Durées du vol')
plt.xlabel('Durée du vol (minutes)')
plt.ylabel('Fréquence')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

plt.figure(figsize=(9, 5))
sns.countplot(x=combined_df['Nombre d\'escales'].dropna())
plt.title('Distribution du Nombre d\'escales')
plt.xlabel('Nombre d\'escales')
plt.ylabel('Nombre de vols')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Corrélation entre la durée et le prix du vol"""

import matplotlib.pyplot as plt
import seaborn as sns

# Filter data by currency
df_mga_scatter = combined_df[combined_df['Currency'] == 'MGA'].dropna(subset=['Durée du vol (minutes)', 'Prix du vol (numérique)'])
df_eur_scatter = combined_df[combined_df['Currency'] == 'EUR'].dropna(subset=['Durée du vol (minutes)', 'Prix du vol (numérique)'])

# MGA
if not df_mga_scatter.empty:
    plt.figure(figsize=(18, 8))
    sns.scatterplot(x='Durée du vol (minutes)', y='Prix du vol (numérique)', hue='Destination', data=df_mga_scatter)
    plt.title('Relation entre la Durée du vol et le Prix du vol (MGA)')
    plt.xlabel('Durée du vol (minutes)')
    plt.ylabel('Prix du vol (MGA)')
    plt.gca().yaxis.set_major_formatter(mga_formatter)
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.legend(bbox_to_anchor=(1.02, 1), loc='upper left', borderaxespad=0., ncol=4, fontsize='small')
    plt.tight_layout()
    plt.show()
else:
    print("Aucune donnée MGA pour le nuage de points.")

# EUR
if not df_eur_scatter.empty:
    plt.figure(figsize=(18, 8))
    sns.scatterplot(x='Durée du vol (minutes)', y='Prix du vol (numérique)', hue='Destination', data=df_eur_scatter)
    plt.title('Relation entre la Durée du vol et le Prix du vol (EUR)')
    plt.xlabel('Durée du vol (minutes)')
    plt.ylabel('Prix du vol (EUR)')
    plt.gca().yaxis.set_major_formatter(eur_formatter)
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.legend(bbox_to_anchor=(1.02, 1), loc='upper left', borderaxespad=0., ncol=4, fontsize='small')
    plt.tight_layout()
    plt.show()
else:
    print("Aucune donnée EUR pour le nuage de points.")

# Calcul du coefficient de corrélation de Pearson
correlation = combined_df['Durée du vol (minutes)'].corr(combined_df['Prix du vol (numérique)'])
print(f"\nCoefficient de corrélation de Pearson entre la Durée du vol et le Prix du vol : {correlation:.2f}")

"""### Interprétation de la corrélation

Le nuage de points et le coefficient de corrélation nous aideront à comprendre si les vols plus longs ont tendance à être plus chers (corrélation positive), moins chers (corrélation négative) ou s'il n'y a pas de relation claire (corrélation proche de zéro).

### Identification des vols les plus chers
"""

# Trier les vols par prix décroissant pour trouver les plus chers
top_10_expensive_flights = combined_df.sort_values(by='Prix du vol (numérique)', ascending=False).head(10)
print("Top 10 des vols les plus chers :")
display(top_10_expensive_flights[['Destination', 'Prix du vol (numérique)', 'Durée du vol', 'Escales']])

# Graphique à barres pour les 10 vols les plus chers
plt.figure(figsize=(12, 7))
sns.barplot(x='Prix du vol (numérique)', y='Destination', data=top_10_expensive_flights, palette='viridis', hue='Destination', legend=False)
plt.title('Top 10 des vols les plus chers (MGA)')
plt.xlabel('Prix du vol (MGA)')
plt.ylabel('Destination')
plt.gca().xaxis.set_major_formatter(mga_formatter)
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Identification des vols les moins chers"""

# Trier les vols par prix croissant pour trouver les moins chers
top_10_cheapest_flights = combined_df.sort_values(by='Prix du vol (numérique)', ascending=True).head(10)
print("Top 10 des vols les moins chers :")
display(top_10_cheapest_flights[['Destination', 'Prix du vol (numérique)', 'Durée du vol', 'Escales']])

# Graphique à barres pour les 10 vols les moins chers
plt.figure(figsize=(12, 7))
sns.barplot(x='Prix du vol (numérique)', y='Destination', data=top_10_cheapest_flights, palette='viridis', hue='Destination', legend=False)
plt.title('Top 10 des vols les moins chers (EUR)')
plt.xlabel('Prix du vol (EUR)')
plt.ylabel('Destination')
plt.gca().xaxis.set_major_formatter(eur_formatter)
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Corrélation entre toutes les colonnes numériques (Heatmap)

Pour une vue d'ensemble des relations linéaires entre toutes les variables numériques, nous allons générer une carte de chaleur (heatmap) de la matrice de corrélation.
"""

# Sélectionner uniquement les colonnes numériques
numerical_cols = ['Prix du vol (numérique)', 'Durée du vol (minutes)', 'Nombre d\'escales']
correlation_matrix = combined_df[numerical_cols].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Matrice de Corrélation des Variables Numériques')
plt.show()

"""### Impact du Nombre d'Escales sur le Prix du Vol

Pour évaluer l'influence du nombre d'escales sur le prix du vol, nous allons utiliser un graphique en boîtes (box plot). Ce graphique montrera la distribution des prix pour chaque catégorie d'escales (0, 1, 2, etc.), ce qui permettra de visualiser les médianes, les quartiles et les valeurs aberrantes.
"""

# MGA
if not df_mga.empty:
    plt.figure(figsize=(10, 6))
    sns.boxplot(x='Nombre d\'escales', y='Prix du vol (numérique)', data=df_mga)
    plt.title('Impact du Nombre d\'Escales sur le Prix du Vol (MGA)')
    plt.xlabel('Nombre d\'Escales')
    plt.ylabel('Prix du vol (MGA)')
    plt.gca().yaxis.set_major_formatter(mga_formatter)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()
else:
    print("Aucune donnée MGA pour le box plot.")

# EUR
if not df_eur.empty:
    plt.figure(figsize=(10, 6))
    sns.boxplot(x='Nombre d\'escales', y='Prix du vol (numérique)', data=df_eur)
    plt.title('Impact du Nombre d\'Escales sur le Prix du Vol (EUR)')
    plt.xlabel('Nombre d\'Escales')
    plt.ylabel('Prix du vol (EUR)')
    plt.gca().yaxis.set_major_formatter(eur_formatter)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()
else:
    print("Aucune donnée EUR pour le box plot.")